name: AutoRestart
version: ${version}
main: net.cchaven.autorestart.AutoRestart
api-version: 1.21

commands:
  autorestart:
    description: Manage AutoRestart plugin
    usage: /autorestart <reload | restart [delayInMinutes] | cancel>
    permission: autorestart
    aliases:
      - ar

permissions:
  autorestart.reload:
    description: Allows reloading of the AutoRestart config
    default: op # All players can use this, but modify as needed

  autorestart.restart:
    description: Allows manually restarting the server via command
    default: op # Restrict this to server operators by default

  autorestart.cancel:
    description: Allows canceling the scheduled restart
    default: op # Restrict this to server operators by default

